### ISSUE TITLE
More flexible functions

### ISSUE THREAD

**Issue by Alexnortung** [olrtg/nvim-rename-state#6]
I have just tried this plugin and it works nicely and I am sure I will use it a lot when using react.

I think I need some more functions to be available, such as:

`:RenameStateEmpty`: Renaming a state but the prompt is empty when starting to write

Or

`:RenmaeState <new name>`: be able to type the new variable name after the name of the command.

**Comment by olrtg** [comment]
Hey! This sounds interesting.. I'll try to pull this off this weekend 🤘🏽

**Comment by Alexnortung** [comment]
Awesome, thanks! 😎

Den 27. oktober 2022 03.50.50 CEST, "José Olórtegui" ***@***.***> skrev:
